import Head from 'next/head'
import Box from '@mui/material/Box';
import Paper from '@mui/material/Paper';
import Grid from '@mui/material/Grid';
import Button from '@mui/material/Button';
import Typography from '@mui/material/Typography';


export default function Home() {
  return (
    <>
      <Head>
        <title>Active FM</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box sx={{height:"410px"}}>
    
    <Typography variant="h3" color="error">Home</Typography>
   
   </Box>
     
    </>

  )
}
